// Auto-generated by scripts/generateImportMap.js
export const importMap = {
  "Core/FileBrowser/frontend/page.tsx": () =>
    import("../../module_system/Core/FileBrowser/frontend/page.tsx"),
  "Core/Terminal/frontend/page.tsx": () =>
    import("../../module_system/Core/Terminal/frontend/page.tsx"),
};
