// Auto-generated by scripts/generateImportMap.js
export const importMap = {
  "Core/FileBrowser/frontend/page.tsx": () => import("../../module_system/Core/FileBrowser/frontend/page.tsx"),
  "Core/ModManager/frontend/page.tsx": () => import("../../module_system/Core/ModManager/frontend/page.tsx"),
  "Core/ModUpdater/frontend/page.tsx": () => import("../../module_system/Core/ModUpdater/frontend/page.tsx"),
  "Core/Terminal/frontend/page.tsx": () => import("../../module_system/Core/Terminal/frontend/page.tsx"),
  "Core/TestModule/frontend/page.tsx": () => import("../../module_system/Core/TestModule/frontend/page.tsx"),
};
